/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QUANLICUAHANGXEMAYGUI;

import java.util.ArrayList;
import java.util.Vector;
import QUANLICUAHANGXEMAYDLL.NhanVienDLL;
import QUANLICUAHANGXEMAYEntity.NhanVien;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author duy
 */
public class NhanVienGUI extends javax.swing.JFrame {

    ArrayList<NhanVien> listNV = new ArrayList<>();
    NhanVienDLL NVdll = new NhanVienDLL();
    boolean them;
    int row_table = -1;
    long count, soTrang, trang = 1;

    void demrow() {
        count = NVdll.CountDb();
        if (count % 5 == 0) {
            soTrang = count / 5;
        } else {
            soTrang = count / 5 + 1;
        }
        lblsotrang.setText(trang + "/" + soTrang);
        lbltrang.setText(trang + "");
    }

    /**
     * Creates new form NhanVien
     */
    private void init() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addElement("Giám đốc");
        model.addElement("Trưởng phòng");
        model.addElement("Nhân viên");
        model.setSelectedItem(model.getElementAt(0));
        cbbchucvu.setModel(model);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        Date date = new Date();
        datechoosengaysinh.setDate(date);
        datechoosengayvl.setDate(date);
    }

    public NhanVienGUI() {
        initComponents();
        Biding();
        init();
        tblNhanVien.setDefaultEditor(Object.class, null);
        demrow();

    }

    public void Biding() {
        Vector column = new Vector();
        column.add("Mã nhân viên");
        column.add("Tên nhân viên");
        column.add("Ngày sinh");
        column.add("Giới tính");
        column.add("Địa chỉ");
        column.add("Điện thoại");
        column.add("Chức vụ");
        column.add("Lương cơ bản");
        column.add("Ngày vào làm");
        column.add("Lương");

        Vector data = new Vector();
        listNV = NVdll.getALL(" 5 ", " [MaNhanVien] not in (SELECT top " + (trang * 5 - 5) + " [MaNhanVien] from dbo.NhanVien )", " MaNhanVien ASC");
        for (NhanVien nv : listNV) {
            Vector row = new Vector();
            row.add(nv.getMaNhanVien());
            row.add(nv.getTenNhanVien());
            row.add(nv.getNgaySinh());
            row.add(nv.getGioiTinh());
            row.add(nv.getDiaChi());
            row.add(nv.getDienThoai());
            row.add(nv.getChucvu());
            row.add(nv.getLuongCoBan());
            row.add(nv.getNgayvaolam());
            row.add(nv.getLuong());
            data.add(row);
        }
        DefaultTableModel dtm = new DefaultTableModel(data, column);
        tblNhanVien.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txttennv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtmanv = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rdbtnnam = new javax.swing.JRadioButton();
        rdbtnnu = new javax.swing.JRadioButton();
        txtdc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtdienthoai = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbbchucvu = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtluongcoban = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtluong = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnlammoi = new javax.swing.JButton();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnluu = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        datechoosengayvl = new com.toedter.calendar.JDateChooser();
        datechoosengaysinh = new com.toedter.calendar.JDateChooser();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lbltrang = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        lblsotrang = new javax.swing.JLabel();

        setFocusable(false);

        jPanel1.setLayout(new java.awt.GridLayout(1, 1));

        jLabel1.setBackground(java.awt.Color.cyan);
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nhân viên");
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel1);

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        jLabel2.setText("Tên nhân viên");

        txttennv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttennvActionPerformed(evt);
            }
        });

        jLabel3.setText("Ngày sinh");

        jLabel4.setText("Mã nhân viên");

        txtmanv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmanvActionPerformed(evt);
            }
        });

        jLabel5.setText("Giới tinh");

        jLabel6.setText("Địa chỉ");

        buttonGroup1.add(rdbtnnam);
        rdbtnnam.setSelected(true);
        rdbtnnam.setText("Nam");
        rdbtnnam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnnamActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbtnnu);
        rdbtnnu.setText("Nữ");

        txtdc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdcActionPerformed(evt);
            }
        });

        jLabel7.setText("Điện thoại");

        jLabel8.setText("Chức vụ");

        cbbchucvu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbchucvu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbchucvuActionPerformed(evt);
            }
        });

        jLabel9.setText("Ngày vào làm");

        jLabel10.setText("Lương cơ bản");

        txtluongcoban.setEnabled(false);
        txtluongcoban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtluongcobanActionPerformed(evt);
            }
        });

        jLabel11.setText("Lương");

        txtluong.setEnabled(false);

        jPanel3.setLayout(null);

        btnlammoi.setText("Làm mới");
        btnlammoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlammoiActionPerformed(evt);
            }
        });
        jPanel3.add(btnlammoi);
        btnlammoi.setBounds(190, 10, 100, 50);

        btnthem.setText("Thêm");
        btnthem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });
        jPanel3.add(btnthem);
        btnthem.setBounds(370, 10, 60, 50);

        btnsua.setText("Sửa");
        btnsua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });
        jPanel3.add(btnsua);
        btnsua.setBounds(620, 10, 70, 50);

        btnxoa.setText("Xoá");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });
        jPanel3.add(btnxoa);
        btnxoa.setBounds(770, 10, 80, 50);

        btnluu.setText("Lưu");
        btnluu.setToolTipText("");
        btnluu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluuActionPerformed(evt);
            }
        });
        jPanel3.add(btnluu);
        btnluu.setBounds(490, 10, 70, 50);

        jLabel12.setText("Tìm kiếm theo tên nhân viên");

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
        });

        jButton1.setText("Tìm kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        datechoosengayvl.setDateFormatString("dd/MM/yyyy");

        datechoosengaysinh.setDateFormatString("dd/MM/yyyy");

        jButton6.setText("<<");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton4.setText("<");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        lbltrang.setText("jLabel2");

        jButton5.setText(">");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setText(">>");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        lblsotrang.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)
                            .addComponent(datechoosengayvl, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(datechoosengaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(60, 60, 60)
                                .addComponent(rdbtnnam)
                                .addGap(41, 41, 41)
                                .addComponent(rdbtnnu))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttennv, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmanv, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 543, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtdienthoai)
                    .addComponent(cbbchucvu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtluongcoban)
                    .addComponent(txtluong)
                    .addComponent(txtdc, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(39, 39, 39)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbltrang)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblsotrang, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtdc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtdienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbbchucvu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtmanv, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttennv, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(datechoosengaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtluongcoban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltrang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblsotrang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbtnnam)
                            .addComponent(rdbtnnu))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel11)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(7, 7, 7)
                                    .addComponent(datechoosengayvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtluong, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttennvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttennvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttennvActionPerformed
    void LamMoi() {
        txtmanv.requestFocus();
        btnluu.setEnabled(true);
        btnsua.setEnabled(true);
        btnxoa.setEnabled(true);
        btnthem.setEnabled(true);
        txtmanv.setEnabled(true);
        txtdc.setText("");
        txtdienthoai.setText("");
        txtmanv.setText("");
        txttennv.setText("");
        txtluong.setText("");
        txtluongcoban.setText("");
        cbbchucvu.setSelectedIndex(0);
        datechoosengaysinh.setDate(new Date());
        datechoosengayvl.setDate(new Date());
        row_table = -1;
    }
    private void btnlammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlammoiActionPerformed
        // TODO add your handling code here:
        trang = 1;
        demrow();
        Biding();
        LamMoi();

    }//GEN-LAST:event_btnlammoiActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:

        btnsua.setEnabled(false);
        btnxoa.setEnabled(false);
        them = true;


    }//GEN-LAST:event_btnthemActionPerformed

    private void cbbchucvuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbchucvuActionPerformed
        // TODO add your handling code here:
        int ngayvaolam, luong;
        switch (cbbchucvu.getSelectedIndex()) {
            case 0: {
                txtluongcoban.setText("5000000");
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy");
                ngayvaolam = Integer.parseInt(dateFormat.format(datechoosengayvl.getDate()));
                luong = (ngayvaolam - 2010) * 500000 + 5000000;
                txtluong.setText(Integer.toString(luong));
                break;
            }
            case 1: {
                txtluongcoban.setText("4000000");
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy");

                ngayvaolam = Integer.parseInt(dateFormat.format(datechoosengayvl.getDate()));
                luong = (ngayvaolam - 2010) * 300000 + 4000000;
                txtluong.setText(Integer.toString(luong));
                break;
            }
            default: {
                txtluongcoban.setText("3000000");
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy");
                ngayvaolam = Integer.parseInt(dateFormat.format(datechoosengayvl.getDate()));
                luong = (ngayvaolam - 2010) * 200000 + 3000000;
                txtluong.setText(Integer.toString(luong));
                break;
            }
        }
    }//GEN-LAST:event_cbbchucvuActionPerformed

    private void txtluongcobanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtluongcobanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtluongcobanActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        NhanVien nv = new NhanVien();
        if (row_table >= 0) {
            nv.setMaNhanVien(tblNhanVien.getValueAt(row_table, 0).toString());
            int dialogResult = JOptionPane.showConfirmDialog(this, "Bạn muốn xóa bản ghi?", "Cảnh báo", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                if (NVdll.deleteData(nv)) {
                    demrow();
                    if (row_table == 0) {
                        trang = soTrang;
                    } else {
                        trang = Integer.parseInt(lbltrang.getText());
                    }
                    demrow();
                    Biding();
                    JOptionPane.showMessageDialog(this, "Xóa thành công!");
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa không thành công!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chọn bạn ghi cần xóa trước");
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluuActionPerformed
        // TODO add your handling code here:

        if (them == true) {

            if (txtmanv.getText().equals("") == false || txttennv.getText().equals("") == false) {
                ArrayList dong = NVdll.CheckID(txtmanv.getText());
                if (dong.size() != 0) {
                    JOptionPane.showMessageDialog(this, "Mã nhân viên đã bị trùng mời bạn nhâp lại!!!");
                    return;
                } else {
                    try {

                        NhanVien nv = new NhanVien();
                        nv.setMaNhanVien(txtmanv.getText());
                        nv.setTenNhanVien(txttennv.getText());

//                        DateFormat formatter=new SimpleDateFormat("yyyy/MM/dd");
//                       
//                        
//                        nv.setNgaySinh(formatter.format(datechoosengaysinh.getDate()));
//                        nv.setNgayvaolam(formatter.format(datechoosengayvl.getDate()));
                        nv.setNgaySinh(DateFormat.getDateInstance().format(datechoosengaysinh.getDate()));
                        nv.setNgayvaolam(DateFormat.getDateInstance().format(datechoosengayvl.getDate()));
                        if (rdbtnnam.isSelected()) {
                            nv.setGioiTinh("Nam");
                        } else {
                            nv.setGioiTinh("Nữ");
                        }

                        nv.setDiaChi(txtdc.getText());
                        nv.setDienThoai(txtdienthoai.getText());
                        nv.setLuong(txtluong.getText());
                        nv.setLuongCoBan(txtluongcoban.getText());
                        nv.setChucvu(cbbchucvu.getSelectedItem().toString());
                        NVdll.AddData(nv);
                        demrow();
                        trang = soTrang;
                        demrow();
                        Biding();
                    } catch (Exception e) {

                    }

                    JOptionPane.showMessageDialog(this, "Thêm thành công!!!");

                }
            } else {
                JOptionPane.showMessageDialog(this, "Bạn bắt buộc phải nhập mã nhân viên và tên nhân viên");
                return;
            }

        } else {
            try {
                NhanVien nv = new NhanVien();
                nv.setMaNhanVien(txtmanv.getText());
                nv.setTenNhanVien(txttennv.getText());
                nv.setNgaySinh(DateFormat.getDateInstance().format(datechoosengaysinh.getDate()));
                if (rdbtnnam.isSelected()) {
                    nv.setGioiTinh("Nam");
                } else {
                    nv.setGioiTinh("Nữ");
                }
                nv.setNgayvaolam(DateFormat.getDateInstance().format(datechoosengayvl.getDate()));
                nv.setDiaChi(txtdc.getText());
                nv.setDienThoai(txtdienthoai.getText());
                nv.setLuong(txtluong.getText());
                nv.setLuongCoBan(txtluongcoban.getText());
                nv.setChucvu(cbbchucvu.getSelectedItem().toString());
                if (NVdll.updateData(nv) == true) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công!!!");
                } else {
                    JOptionPane.showMessageDialog(this, "Bạn chưa chọn điều khiển!!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                Biding();

            } catch (Exception e) {

            }

        }
        LamMoi();


    }//GEN-LAST:event_btnluuActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        if (row_table < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập dòng của bảng muốn sửa!!!");
            return;
        } else {
            txtmanv.setEnabled(false);
            them = false;
            btnthem.setEnabled(false);
            btnxoa.setEnabled(false);
            // listNV = NVdll.getALL("", "", "");
            txtmanv.setText(listNV.get(row_table).getMaNhanVien());
            txttennv.setText(listNV.get(row_table).getTenNhanVien());
            txtdc.setText(listNV.get(row_table).getDiaChi());
            txtdienthoai.setText(listNV.get(row_table).getDienThoai());
            DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            try {

                Date date = formatter.parse(listNV.get(row_table).getNgaySinh());
                datechoosengaysinh.setDate(date);
            } catch (ParseException ex) {
                Logger.getLogger(NhanVienGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {

                Date date = formatter.parse(listNV.get(row_table).getNgayvaolam());
                datechoosengayvl.setDate(date);
            } catch (ParseException ex) {
                Logger.getLogger(NhanVienGUI.class.getName()).log(Level.SEVERE, null, ex);

            }
            //DefaultTableModel model2 = (DefaultTableModel) tblNhanVien.getModel();
            //   cboLoai.setSelectedItem(tbl.getValueAt(r, 4).toString().trim());

            String s = tblNhanVien.getValueAt(row_table, 6).toString().trim();
            cbbchucvu.setSelectedItem(s);
//            if(s.toLowerCase().equals(("Trưởng phòng").toLowerCase())==true)
//            cbbchucvu.setSelectedIndex(1);
            txtluong.setText(listNV.get(row_table).getLuong());
            txtluongcoban.setText(listNV.get(row_table).getLuongCoBan());
            if (listNV.get(row_table).getGioiTinh().equals("Nam")) {
                rdbtnnam.setSelected(true);
            } else {
                rdbtnnu.setSelected(true);
            }
    }//GEN-LAST:event_btnsuaActionPerformed
    }
    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        // TODO add your handling code here:

        row_table = tblNhanVien.getSelectedRow();

    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void rdbtnnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnnamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbtnnamActionPerformed

    private void txtdcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdcActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtSearchActionPerformed
    void timkiem() {
        Vector column = new Vector();
        column.add("Mã nhân viên");
        column.add("Tên nhân viên");
        column.add("Ngày sinh");
        column.add("Giới tính");
        column.add("Địa chỉ");
        column.add("Điện thoại");
        column.add("Chức vụ");
        column.add("Lương cơ bản");
        column.add("Ngày vào làm");
        column.add("Lương");

        Vector data = new Vector();
        listNV = NVdll.getALL("", " dbo.fuChuyenCoDauThanhKhongDau(TenNhanVien) like N'%'+dbo.fuChuyenCoDauThanhKhongDau(N'" + txtSearch.getText() + "')+'%'", "");
        for (NhanVien nv : listNV) {
            Vector row = new Vector();
            row.add(nv.getMaNhanVien());
            row.add(nv.getTenNhanVien());
            row.add(nv.getNgaySinh());
            row.add(nv.getGioiTinh());
            row.add(nv.getDiaChi());
            row.add(nv.getDienThoai());
            row.add(nv.getChucvu());
            row.add(nv.getLuongCoBan());
            row.add(nv.getNgayvaolam());
            row.add(nv.getLuong());
            data.add(row);
        }
        DefaultTableModel dtm = new DefaultTableModel(data, column);
        tblNhanVien.setModel(dtm);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        timkiem();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtmanvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmanvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmanvActionPerformed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            timkiem();
        }
    }//GEN-LAST:event_txtSearchKeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        trang = 1;
        Biding();
        lbltrang.setText("1");
        lblsotrang.setText("1/" + soTrang);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (trang > 1) {
            trang--;
            Biding();
            lbltrang.setText("" + trang);
            lblsotrang.setText(trang + "/" + soTrang);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (trang < soTrang) {
            trang++;
            Biding();
            lbltrang.setText("" + trang);
            lblsotrang.setText(trang + "/" + soTrang);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        trang = soTrang;
        Biding();
        lbltrang.setText("" + trang);
        lblsotrang.setText(trang + "/" + soTrang);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVienGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlammoi;
    private javax.swing.JButton btnluu;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbchucvu;
    private com.toedter.calendar.JDateChooser datechoosengaysinh;
    private com.toedter.calendar.JDateChooser datechoosengayvl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblsotrang;
    private javax.swing.JLabel lbltrang;
    private javax.swing.JRadioButton rdbtnnam;
    private javax.swing.JRadioButton rdbtnnu;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtdc;
    private javax.swing.JTextField txtdienthoai;
    private javax.swing.JTextField txtluong;
    private javax.swing.JTextField txtluongcoban;
    private javax.swing.JTextField txtmanv;
    private javax.swing.JTextField txttennv;
    // End of variables declaration//GEN-END:variables
}
