/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QUANLICUAHANGXEMAYGUI;

import QUANLICUAHANGXEMAYDLL.ChiTietPhieuNhapDLL;
import QUANLICUAHANGXEMAYDLL.PhieuNhapDLL;
import QUANLICUAHANGXEMAYEntity.ChiTietPhieuNhap;
import QUANLICUAHANGXEMAYEntity.PhieuNhap;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author duy
 */
public class PhieuNhapGUI extends javax.swing.JFrame {

    ArrayList<PhieuNhap> listPhieuNhap = new ArrayList<>();
    ArrayList<ChiTietPhieuNhap> listChiTietPhieuNhap = new ArrayList<>();
    PhieuNhapDLL PhieuNhapdll = new PhieuNhapDLL();
    ChiTietPhieuNhapDLL CTPNdll = new ChiTietPhieuNhapDLL();
    boolean them_PhieuNhap = true;
    boolean them_CTPN;
    int row_table_PhieuNhap = -1;
    int row_table_CTPN = -1;
    public static String manhanvien;
    public static int value = 3;

    /**
     * Creates new form PhieuNhapGUI
     */
    public PhieuNhapGUI() {
        initComponents();
        Biding_PhieuNhap();
        Biding_ChiTietPhieuNhap();
        txtmanhanvien.setEnabled(false);
        txtmanhanvien.setText(manhanvien);
        Date date = new Date();
        datechooserngaynhapnam.setDate(date);
        txtmachitietpn.setEnabled(false);
        tblphieunhap.setDefaultEditor(Object.class, null);
        tblchitietphieunhap.setDefaultEditor(Object.class, null);
        //   Biding_ChiTietPhieuNhap();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtmachitietpn = new javax.swing.JTextField();
        cbbmaxe = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        spnsoluong = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        txtdongia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtthue = new javax.swing.JTextField();
        btnluu = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnthem = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblchitietphieunhap = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        txtsearchhd = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        cbbmanhanhacungcap = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtmanhanvien = new javax.swing.JTextField();
        txtmaphieunhap = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        datechooserngaynhapnam = new com.toedter.calendar.JDateChooser();
        jLabel37 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblphieunhap = new javax.swing.JTable();
        jButton20 = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi Tiết Phiếu Nhập", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N

        jLabel6.setText("Mã phiếu nhập");

        cbbmaxe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbmaxeMouseClicked(evt);
            }
        });
        cbbmaxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbmaxeActionPerformed(evt);
            }
        });

        jLabel7.setText("Mã xe");

        jLabel8.setText("Số lượng");

        jLabel9.setText("Đơn giá");

        jLabel10.setText("Thuế");

        btnluu.setText("Lưu");
        btnluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluuActionPerformed(evt);
            }
        });

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setText("Xoá");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        jButton8.setText("Làm mới");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnluu, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnsoluong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbmaxe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmachitietpn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(124, 124, 124)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtthue, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtdongia, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtdongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtmachitietpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbmaxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(txtthue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(spnsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnluu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        tblchitietphieunhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblchitietphieunhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblchitietphieunhapMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblchitietphieunhap);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phiếu Nhập", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N

        jButton18.setText("Tìm kiếm");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        txtsearchhd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchhdKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );

        cbbmanhanhacungcap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbmanhanhacungcapMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbbmanhanhacungcapMousePressed(evt);
            }
        });
        cbbmanhanhacungcap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbmanhanhacungcapActionPerformed(evt);
            }
        });

        jLabel35.setText("Mã nhà cung cấp");

        jLabel36.setText("Mã nhân viên");

        txtmanhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmanvActionPerformed(evt);
            }
        });

        jLabel33.setText("Mã phiếu nhập");

        jLabel34.setText("Ngày nhập");

        datechooserngaynhapnam.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtmanhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datechooserngaynhapnam, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtmaphieunhap, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbbmanhanhacungcap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(cbbmanhanhacungcap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmanhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36)
                            .addComponent(jLabel33)
                            .addComponent(txtmaphieunhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(datechooserngaynhapnam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel37.setText("Tìm kiếm theo mã phiếu nhập");

        jButton17.setText("Làm mới");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton19.setText("Thêm");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        tblphieunhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblphieunhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblphieunhapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblphieunhap);

        jButton20.setText("Sửa");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(99, 99, 99))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel37)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtsearchhd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26)
                                    .addComponent(jButton18)
                                    .addGap(68, 68, 68)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtsearchhd, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel37))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 540, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Biding_PhieuNhap() {
        Vector column = new Vector();
        column.add("Mã Phiếu nhập");
        column.add("Mã nhân viên");
        column.add("Mã nhà cung cấp");
        column.add("Ngày nhập");

        Vector data = new Vector();
        listPhieuNhap = PhieuNhapdll.getALL("", "", "");
        for (PhieuNhap kh : listPhieuNhap) {
            Vector row = new Vector();
            row.add(kh.getMaPhieuNhap());
            row.add(kh.getMaNhanVien());
            row.add(kh.getMaNhaCungCap());
            row.add(kh.getNgayNhap());
            data.add(row);
        }
        DefaultTableModel dtm = new DefaultTableModel(data, column);
        tblphieunhap.setModel(dtm);
    }

    public void Biding_ChiTietPhieuNhap() {
        Vector column = new Vector();
        column.add("Mã Phiếu nhập");
        column.add("Mã Xe");
        column.add("Số lượng");
        column.add("Đơn giá nhập");
        column.add("Thuế");
        column.add("Thành tiền");
        Vector data = new Vector();
        listChiTietPhieuNhap = CTPNdll.getALL("", "", "");
        for (ChiTietPhieuNhap kh : listChiTietPhieuNhap) {
            Vector row = new Vector();
            row.add(kh.getMaPhieuNhap());
            row.add(kh.getMaXe());
            row.add(kh.getSLNhap());
            row.add(kh.getDonGiaNhap());
            row.add(kh.getThue());
            row.add(kh.getThanhTien());
            data.add(row);
        }
        DefaultTableModel dtm = new DefaultTableModel(data, column);
        tblchitietphieunhap.setModel(dtm);
    }

    void LamMoi_tPhieuNhap() {
        cbbmanhanhacungcap.setSelectedIndex(-1);
        datechooserngaynhapnam.setDate(new Date());
        txtmaphieunhap.requestFocus();
        // spnsoluong.setValue(0);
        txtmaphieunhap.setText("");
        Biding_PhieuNhap();
        txtmaphieunhap.setEnabled(true);
        row_table_PhieuNhap=-1;
        txtsearchhd.setText("");

    }

    void LamMoi_ChiTietPhieuNhap() {
        btnluu.setEnabled(true);
        btnsua.setEnabled(true);
        btnxoa.setEnabled(true);
        btnthem.setEnabled(true);
        txtdongia.setText("");
        txtthue.setText("");
        spnsoluong.setValue(0);
        txtmachitietpn.setText("");
        cbbmaxe.setSelectedIndex(-1);
        // spnsoluong.setValue(0);
        cbbmaxe.setEnabled(true);
        row_table_CTPN=-1;
    }

    private void cbbmaxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbmaxeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbmaxeActionPerformed

    private void txtmanvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmanvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmanvActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        LamMoi_tPhieuNhap();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void cbbmanhanhacungcapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbmanhanhacungcapActionPerformed

        // TODO add your handling code here:

    }//GEN-LAST:event_cbbmanhanhacungcapActionPerformed

    private void cbbmanhanhacungcapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbmanhanhacungcapMouseClicked
        // TODO add your handling code here:
        TableNhaCungCap tblncc = new TableNhaCungCap();
        tblncc.setVisible(true);

    }//GEN-LAST:event_cbbmanhanhacungcapMouseClicked

    private void cbbmanhanhacungcapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbmanhanhacungcapMousePressed
        // TODO add your handling code here:
//       TableNhaCungCap tblncc=new TableNhaCungCap();
//       tblncc.setVisible(true);
    }//GEN-LAST:event_cbbmanhanhacungcapMousePressed

    private void cbbmaxeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbmaxeMouseClicked
        // TODO add your handling code here:
        TableXe tblncc = new TableXe();
        value = 0;
        tblncc.setVisible(true);
    }//GEN-LAST:event_cbbmaxeMouseClicked

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        if (them_PhieuNhap == true) {

            if (txtmaphieunhap.getText().equals("") == true) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập đầy đủ thông tin!!!");
                return;
            } else {
                ArrayList dong = PhieuNhapdll.CheckID(txtmaphieunhap.getText());
                if (dong.size() != 0) {
                    JOptionPane.showMessageDialog(this, "Mã phiếu nhập đã bị trùng mời bạn nhâp lại!!!");
                    return;
                } else {
                    try {
                        PhieuNhap nv = new PhieuNhap();
                        nv.setMaNhanVien(txtmanhanvien.getText());
                        nv.setNgayNhap(DateFormat.getDateInstance().format(datechooserngaynhapnam.getDate()));
                        nv.setMaNhaCungCap(cbbmanhanhacungcap.getSelectedItem().toString());
                        nv.setMaPhieuNhap(txtmaphieunhap.getText());
                        if (PhieuNhapdll.AddData(nv) == true) {
                            JOptionPane.showMessageDialog(this, "Thêm thành công!!!");

                        } else {
                            JOptionPane.showMessageDialog(this, "Bạn đã nhập trùng mã phiếu nhập!!! ");
                            return;
                        }
                    } catch (Exception e) {

                    }

                }
            }

        } else {
            try {
                PhieuNhap nv = new PhieuNhap();
                nv.setMaNhanVien(txtmanhanvien.getText());
                nv.setNgayNhap(DateFormat.getDateInstance().format(datechooserngaynhapnam.getDate()));
                nv.setMaNhaCungCap(cbbmanhanhacungcap.getSelectedItem().toString());
                nv.setMaPhieuNhap(txtmaphieunhap.getText());
                PhieuNhapdll.updateData(nv);
                Biding_PhieuNhap();
                JOptionPane.showMessageDialog(this, "Sửa thành công!!!");
            } catch (Exception e) {

            }
        }
        Biding_PhieuNhap();
        LamMoi_tPhieuNhap();


    }//GEN-LAST:event_jButton19ActionPerformed
    void timkiem_ChiTietPhieuNhap() {
        Vector column = new Vector();
        column.add("Mã Phiếu nhập");
        column.add("Mã Xe");
        column.add("Số lượng");
        column.add("Đơn giá nhập");
        column.add("Thuế");
        column.add("Thành tiền");
        //TenKH like N'%" + txtSearchKH.getText() + "%'
//dbo.fuChuyenCoDauThanhKhongDau(TenNhanVien) like N'%'+dbo.fuChuyenCoDauThanhKhongDau('"+txtSearch.getText()+"')+'%'"
        listChiTietPhieuNhap = CTPNdll.getALL("", "dbo.fuChuyenCoDauThanhKhongDau(MaPN) like N'%'+dbo.fuChuyenCoDauThanhKhongDau('" + listPhieuNhap.get(row_table_PhieuNhap).getMaPhieuNhap() + "')+'%'", "");
        Vector data = new Vector();

        for (ChiTietPhieuNhap kh : listChiTietPhieuNhap) {
            Vector row = new Vector();
            row.add(kh.getMaPhieuNhap());
            row.add(kh.getMaXe());
            row.add(kh.getSLNhap());
            row.add(kh.getDonGiaNhap());
            row.add(kh.getThue());
            row.add(kh.getThanhTien());
            data.add(row);
        }
        DefaultTableModel dtm = new DefaultTableModel(data, column);
        tblchitietphieunhap.setModel(dtm);

    }
    private void tblphieunhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblphieunhapMouseClicked
        // TODO add your handling code here:
        row_table_PhieuNhap = tblphieunhap.getSelectedRow();
        if (them_CTPN == true) {
            txtmachitietpn.setText(listPhieuNhap.get(row_table_PhieuNhap).getMaPhieuNhap());
        }
        timkiem_ChiTietPhieuNhap();
    }//GEN-LAST:event_tblphieunhapMouseClicked

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        them_PhieuNhap = false;
        txtmaphieunhap.setEnabled(false);
        if (row_table_PhieuNhap < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập dòng của bảng muốn sửa!!!");
            return;
        } else {
            txtmaphieunhap.setText(listPhieuNhap.get(row_table_PhieuNhap).getMaPhieuNhap());
            DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            try {

                Date date = formatter.parse(listPhieuNhap.get(row_table_PhieuNhap).getNgayNhap());
                datechooserngaynhapnam.setDate(date);
            } catch (ParseException ex) {
                Logger.getLogger(NhanVienGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            model.addElement(listPhieuNhap.get(row_table_PhieuNhap).getMaNhaCungCap().toString().trim());
            model.setSelectedItem(model.getElementAt(0));
            PhieuNhapGUI.cbbmanhanhacungcap.setModel(model);
            txtmaphieunhap.setEnabled(false);

        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(row_table_PhieuNhap>=0)
        {
            timkiem_ChiTietPhieuNhap();
        }
        else
         Biding_ChiTietPhieuNhap();
        LamMoi_ChiTietPhieuNhap();
       
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        if (row_table_PhieuNhap == -1) {
            JOptionPane.showMessageDialog(this, "Bạn hãy chọn dòng bảng phiếu xuất!!! ", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {
            txtmachitietpn.setText(listPhieuNhap.get(row_table_PhieuNhap).getMaPhieuNhap());
            btnsua.setEnabled(false);
            btnxoa.setEnabled(false);
            them_CTPN = true;
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        if (row_table_CTPN < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập dòng của bảng muốn sửa!!!");
            return;
        } else {

            them_CTPN = false;
//                txtmaphieunhap.setText(listPhieuNhap.get(row_table_PhieuNhap).getMaPhieuNhap());
            txtthue.setText(listChiTietPhieuNhap.get(row_table_CTPN).getThue());
            spnsoluong.setValue(Integer.valueOf(listChiTietPhieuNhap.get(row_table_CTPN).getSLNhap().trim()));
            txtmachitietpn.setText(listChiTietPhieuNhap.get(row_table_CTPN).getMaPhieuNhap());
            txtdongia.setText(listChiTietPhieuNhap.get(row_table_CTPN).getDonGiaNhap());
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            model.addElement(listChiTietPhieuNhap.get(row_table_CTPN).getMaXe().toString().trim());
            model.setSelectedItem(model.getElementAt(0));
            cbbmaxe.setModel(model);
            btnthem.setEnabled(false);
            btnxoa.setEnabled(false);
            cbbmaxe.setEnabled(false);

    }//GEN-LAST:event_btnsuaActionPerformed
    }
    private void tblchitietphieunhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblchitietphieunhapMouseClicked
        // TODO add your handling code here:
        row_table_CTPN = tblchitietphieunhap.getSelectedRow();
    }//GEN-LAST:event_tblchitietphieunhapMouseClicked

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        ChiTietPhieuNhap nv = new ChiTietPhieuNhap();
        if (row_table_CTPN >= 0) {
            nv.setMaPhieuNhap(tblchitietphieunhap.getValueAt(row_table_CTPN, 0).toString());
            nv.setMaXe(tblchitietphieunhap.getValueAt(row_table_CTPN, 1).toString());
            int dialogResult = JOptionPane.showConfirmDialog(this, "Bạn muốn xóa bản ghi?", "Cảnh báo", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                if (CTPNdll.deleteData(nv)) {

                    JOptionPane.showMessageDialog(this, "Xóa thành công!");
                  timkiem_ChiTietPhieuNhap();
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa không thành công!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chọn bạn ghi cần xóa trước");
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluuActionPerformed
        // TODO add your handling code here:
        if (them_CTPN == true) {

            if (Integer.parseInt(spnsoluong.getValue().toString()) == 0||cbbmaxe.getSelectedItem()==null) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập đầy đủ thông tin!!!");
                return;
            } else {

                ArrayList dong = CTPNdll.CheckID(txtmachitietpn.getText(), cbbmaxe.getSelectedItem().toString());
                if (dong.size() != 0) {
                    JOptionPane.showMessageDialog(this, "Mã phiếu nhập đã bị trùng mời bạn nhâp lại!!!");
                    return;
                } else {
                    try {
                        ChiTietPhieuNhap nv = new ChiTietPhieuNhap();
                        nv.setMaPhieuNhap(txtmachitietpn.getText());
                        nv.setMaXe(cbbmaxe.getSelectedItem().toString());
                        nv.setSLNhap(spnsoluong.getValue().toString());
                        nv.setDonGiaNhap(txtdongia.getText());
                        nv.setThue(txtthue.getText());
                        if (CTPNdll.AddData(nv) == true) {
                            JOptionPane.showMessageDialog(this, "Thêm thành công!!!");
                        } else {
                            JOptionPane.showMessageDialog(this, "Bạn đã nhập trùng Mã Phiếu Nhập");
                        }

                    } catch (Exception e) {

                    }

                }
            }

        } else {
            try {
                ChiTietPhieuNhap nv = new ChiTietPhieuNhap();
                nv.setMaPhieuNhap(txtmachitietpn.getText());
                nv.setMaXe(cbbmaxe.getSelectedItem().toString());
                nv.setSLNhap(spnsoluong.getValue().toString());
                nv.setDonGiaNhap(txtdongia.getText());
                nv.setThue(txtthue.getText());
                if (CTPNdll.updateData(nv) == true) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công!!!");
                } else {
                    JOptionPane.showMessageDialog(this, "Bạn chưa chọn điều khiển!!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    return;
                }

            } catch (Exception e) {

            }

        }
        LamMoi_ChiTietPhieuNhap();
        timkiem_ChiTietPhieuNhap();
    }//GEN-LAST:event_btnluuActionPerformed
    void timkiem_PhieuNhap() {

        Vector column = new Vector();
        column.add("Mã Phiếu nhập");
        column.add("Mã nhân viên");
        column.add("Mã nhà cung cấp");
        column.add("Ngày nhập");

        Vector data = new Vector();
        listPhieuNhap = PhieuNhapdll.getALL("", "dbo.fuChuyenCoDauThanhKhongDau(MaPN) like N'%'+dbo.fuChuyenCoDauThanhKhongDau('" + txtsearchhd.getText() + "')+'%'", "");
        for (PhieuNhap kh : listPhieuNhap) {
            Vector row = new Vector();
            row.add(kh.getMaPhieuNhap());
            row.add(kh.getMaNhanVien());
            row.add(kh.getMaNhaCungCap());
            row.add(kh.getNgayNhap());
            data.add(row);
        }
        DefaultTableModel dtm = new DefaultTableModel(data, column);
        tblphieunhap.setModel(dtm);
    }


    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        timkiem_PhieuNhap();
    }//GEN-LAST:event_jButton18ActionPerformed

    private void txtsearchhdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchhdKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            timkiem_PhieuNhap();
        }
    }//GEN-LAST:event_txtsearchhdKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhieuNhapGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhieuNhapGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhieuNhapGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhieuNhapGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhieuNhapGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnluu;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    public static javax.swing.JComboBox<String> cbbmanhanhacungcap;
    public static javax.swing.JComboBox<String> cbbmaxe;
    private com.toedter.calendar.JDateChooser datechooserngaynhapnam;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner spnsoluong;
    private javax.swing.JTable tblchitietphieunhap;
    private javax.swing.JTable tblphieunhap;
    public static javax.swing.JTextField txtdongia;
    private javax.swing.JTextField txtmachitietpn;
    private javax.swing.JTextField txtmanhanvien;
    private javax.swing.JTextField txtmaphieunhap;
    private javax.swing.JTextField txtsearchhd;
    private javax.swing.JTextField txtthue;
    // End of variables declaration//GEN-END:variables
}
