/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QUANLICUAHANGXEMAYGUI;

import QUANLICUAHANGXEMAYDLL.ChiTietPhieuXuatDLL;
import QUANLICUAHANGXEMAYDLL.PhieuXuatDLL;
import QUANLICUAHANGXEMAYEntity.ChiTietPhieuXuat;
import QUANLICUAHANGXEMAYEntity.PhieuXuat;
import static QUANLICUAHANGXEMAYGUI.PhieuXuatGUI.cbbmakh;
import QUANLICUAHANGXEMAYGUI.report.Report;
import static QUANLICUAHANGXEMAYGUI.report.Report.s1;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author duy
 */
public class PhieuXuatGUI extends javax.swing.JFrame {

    ArrayList<PhieuXuat> listPhieuXuat = new ArrayList<>();
    ArrayList<ChiTietPhieuXuat> listChiTietPhieuXuat = new ArrayList<>();
    PhieuXuatDLL PhieuXuatdll = new PhieuXuatDLL();
    ChiTietPhieuXuatDLL CTPNdll = new ChiTietPhieuXuatDLL();
    boolean them_PhieuXuat = true;
    boolean them_CTPN;
    int row_table_PhieuXuat = -1;
    int row_table_CTPX = -1;
    public static String manhanvien;
    public static int value = 3;

    /**
     * Creates new form PhieuXuatGUI
     */
    public PhieuXuatGUI() {
        initComponents();
        Biding_PhieuXuat();
        Biding_ChiTietPhieuXuat();
        txtmanhanvien.setEnabled(false);
        txtmanhanvien.setText(manhanvien);
        Date date = new Date();
        datechooserngayxuat.setDate(date);
        txtmahdctpx.setEnabled(false);
        tblchitietphieuxuat.setDefaultEditor(Object.class, null);
        tblphieuxuat.setDefaultEditor(Object.class, null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        txtsearchhd = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        cbbmakh = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtmanhanvien = new javax.swing.JTextField();
        txtmahdpx = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        datechooserngayxuat = new com.toedter.calendar.JDateChooser();
        jLabel37 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblphieuxuat = new javax.swing.JTable();
        jButton20 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtmahdctpx = new javax.swing.JTextField();
        cbbmaxe = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        spnsoluong = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        txtdongia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtthue = new javax.swing.JTextField();
        btnluu = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnthem = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblchitietphieuxuat = new javax.swing.JTable();

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phiếu Xuất", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N

        jButton18.setText("Tìm kiếm");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        txtsearchhd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchhdKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );

        cbbmakh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbmakhMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbbmakhMousePressed(evt);
            }
        });
        cbbmakh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbmakhActionPerformed(evt);
            }
        });

        jLabel35.setText("Mã khách hàng");

        jLabel36.setText("Mã nhân viên");

        txtmanhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmanhanvientxtmanvActionPerformed(evt);
            }
        });

        jLabel33.setText("Mã hoá đơn");

        jLabel34.setText("Ngày xuất");

        datechooserngayxuat.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtmanhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datechooserngayxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtmahdpx, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbbmakh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(cbbmakh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmanhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36)
                            .addComponent(jLabel33)
                            .addComponent(txtmahdpx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(datechooserngayxuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel37.setText("Tìm kiếm theo mã hoá đơn");

        jButton17.setText("Làm mới");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton19.setText("Thêm");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        tblphieuxuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblphieuxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblphieuxuatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblphieuxuat);

        jButton20.setText("Sửa");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton1.setText("In hoá đơn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton19)
                                    .addComponent(jLabel37))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(txtsearchhd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton18)
                                        .addGap(68, 68, 68))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jButton17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(79, 79, 79)))))))
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsearchhd, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37))
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi Tiết Phiếu Xuất", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24))); // NOI18N

        jLabel6.setText("Mã hoá đơn");

        cbbmaxe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbmaxeMouseClicked(evt);
            }
        });
        cbbmaxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbmaxeActionPerformed(evt);
            }
        });

        jLabel7.setText("Mã xe");

        jLabel8.setText("Số lượng");

        jLabel9.setText("Đơn giá");

        jLabel10.setText("Thuế");

        btnluu.setText("Lưu");
        btnluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluuActionPerformed(evt);
            }
        });

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setText("Xoá");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        jButton8.setText("Làm mới");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnluu, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnsoluong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbmaxe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmahdctpx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(124, 124, 124)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtthue, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtdongia, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtdongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtmahdctpx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbmaxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(txtthue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(spnsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnluu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        tblchitietphieuxuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblchitietphieuxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblchitietphieuxuatMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblchitietphieuxuat);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        timkiem_PhieuXuat();
    }//GEN-LAST:event_jButton18ActionPerformed
    public void Biding_PhieuXuat() {
        Vector column = new Vector();
        column.add("Mã hoá đơn");
        column.add("Mã nhân viên");
        column.add("Mã khách hàng");
        column.add("Ngày Xuất");

        Vector data = new Vector();
        listPhieuXuat = PhieuXuatdll.getALL("", "", "");
        for (PhieuXuat kh : listPhieuXuat) {
            Vector row = new Vector();
            row.add(kh.getMaPhieuXuat());
            row.add(kh.getMaNhanVien());
            row.add(kh.getMaKhachHang());
            row.add(kh.getNgayXuat());
            data.add(row);
        }
        DefaultTableModel dtm = new DefaultTableModel(data, column);
        tblphieuxuat.setModel(dtm);
    }

    public void Biding_ChiTietPhieuXuat() {
        Vector column = new Vector();
        column.add("Mã hoá đơn");
        column.add("Mã Xe");
        column.add("Số lượng");
        column.add("Đơn giá Xuất");
        column.add("Thuế");
        column.add("Thành tiền");
        Vector data = new Vector();
        listChiTietPhieuXuat = CTPNdll.getALL("", "", "");
        for (ChiTietPhieuXuat kh : listChiTietPhieuXuat) {
            Vector row = new Vector();
            row.add(kh.getMaPhieuXuat());
            row.add(kh.getMaXe());
            row.add(kh.getSLXuat());
            row.add(kh.getDonGiaXuat());
            row.add(kh.getThue());
            row.add(kh.getThanhTien());
            data.add(row);
        }
        DefaultTableModel dtm = new DefaultTableModel(data, column);
        tblchitietphieuxuat.setModel(dtm);
    }

    void LamMoi_tPhieuXuat() {
        cbbmakh.setSelectedIndex(-1);
        datechooserngayxuat.setDate(new Date());
        txtmahdpx.requestFocus();
        // spnsoluong.setValue(0);
        txtmahdpx.setText("");
        Biding_PhieuXuat();
        txtmahdpx.setEnabled(true);
        row_table_PhieuXuat=-1;
        txtsearchhd.setText("");

    }

    void LamMoi_ChiTietPhieuXuat() {
        btnluu.setEnabled(true);
        btnsua.setEnabled(true);
        btnxoa.setEnabled(true);
        btnthem.setEnabled(true);
        txtdongia.setText("");
        txtthue.setText("");
        spnsoluong.setValue(0);
        txtmahdctpx.setText("");
        cbbmaxe.setSelectedIndex(-1);
        // spnsoluong.setValue(0);
        cbbmaxe.setEnabled(true);
        row_table_CTPX=-1;
    }

    void timkiem_PhieuXuat() {

        Vector column = new Vector();
        column.add("Mã Phiếu Xuất");
        column.add("Mã nhân viên");
        column.add("Mã khách hàng");
        column.add("Ngày Xuất");

        Vector data = new Vector();
        listPhieuXuat = PhieuXuatdll.getALL("", "dbo.fuChuyenCoDauThanhKhongDau(MaPhieuXuat) like N'%'+dbo.fuChuyenCoDauThanhKhongDau('" + txtsearchhd.getText() + "')+'%'", "");
        for (PhieuXuat kh : listPhieuXuat) {
            Vector row = new Vector();
            row.add(kh.getMaPhieuXuat());
            row.add(kh.getMaNhanVien());
            row.add(kh.getMaKhachHang());
            row.add(kh.getNgayXuat());
            data.add(row);
        }
        DefaultTableModel dtm = new DefaultTableModel(data, column);
        tblphieuxuat.setModel(dtm);
    }
    private void txtsearchhdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchhdKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            timkiem_PhieuXuat();
        }
    }//GEN-LAST:event_txtsearchhdKeyPressed

    private void cbbmakhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbmakhMouseClicked
        // TODO add your handling code here:
        TableKhachHang tblncc = new TableKhachHang();
        tblncc.setVisible(true);
    }//GEN-LAST:event_cbbmakhMouseClicked

    private void cbbmakhMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbmakhMousePressed
        // TODO add your handling code here:
        //       TableNhaCungCap tblncc=new TableNhaCungCap();
        //       tblncc.setVisible(true);
    }//GEN-LAST:event_cbbmakhMousePressed

    private void cbbmakhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbmakhActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_cbbmakhActionPerformed

    private void txtmanhanvientxtmanvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmanhanvientxtmanvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmanhanvientxtmanvActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        LamMoi_tPhieuXuat();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        if (them_PhieuXuat == true) {

            if (txtmahdpx.getText().equals("") == true) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập đầy đủ thông tin!!!");
                return;
            } else {
                ArrayList dong = PhieuXuatdll.CheckID(txtmahdpx.getText());
                if (dong.size() != 0) {
                    JOptionPane.showMessageDialog(this, "Mã phiếu nhập đã bị trùng mời bạn nhâp lại!!!");
                    return;
                } else {
                    try {
                        PhieuXuat nv = new PhieuXuat();
                        nv.setMaNhanVien(txtmanhanvien.getText());
                        nv.setNgayXuat(DateFormat.getDateInstance().format(datechooserngayxuat.getDate()));
                        nv.setMaKhachHang(cbbmakh.getSelectedItem().toString());
                        nv.setMaPhieuXuat(txtmahdpx.getText());
                        if (PhieuXuatdll.AddData(nv) == true) {
                            JOptionPane.showMessageDialog(this, "Thêm thành công!!!");
                            Biding_PhieuXuat();
                        } else {
                            JOptionPane.showMessageDialog(this, "Bạn đã nhập trùng mã phiếu nhập!!! ");
                            return;
                        }
                    } catch (Exception e) {

                    }

                }
            }

        } else {
            try {
                PhieuXuat nv = new PhieuXuat();
                nv.setMaNhanVien(txtmanhanvien.getText());
                nv.setNgayXuat(DateFormat.getDateInstance().format(datechooserngayxuat.getDate()));
                nv.setMaKhachHang(cbbmakh.getSelectedItem().toString());
                nv.setMaPhieuXuat(txtmahdpx.getText());
                PhieuXuatdll.updateData(nv);
                Biding_PhieuXuat();
                JOptionPane.showMessageDialog(this, "Sửa thành công!!!");
            } catch (Exception e) {

            }
        }
        LamMoi_tPhieuXuat();
    }//GEN-LAST:event_jButton19ActionPerformed
    void timkiem_ChiTietPhieuXuat() {
        Vector column = new Vector();
        column.add("Mã hoá đơn");
        column.add("Mã Xe");
        column.add("Số lượng");
        column.add("Đơn giá Xuất");
        column.add("Thuế");
        column.add("Thành tiền");
        //TenKH like N'%" + txtSearchKH.getText() + "%'
//dbo.fuChuyenCoDauThanhKhongDau(TenNhanVien) like N'%'+dbo.fuChuyenCoDauThanhKhongDau('"+txtSearch.getText()+"')+'%'"
        listChiTietPhieuXuat = CTPNdll.getALL("", "dbo.fuChuyenCoDauThanhKhongDau(MaPhieuXuat) like N'%'+dbo.fuChuyenCoDauThanhKhongDau('" + listPhieuXuat.get(row_table_PhieuXuat).getMaPhieuXuat() + "')+'%'", "");
        Vector data = new Vector();

        for (ChiTietPhieuXuat kh : listChiTietPhieuXuat) {
            Vector row = new Vector();
            row.add(kh.getMaPhieuXuat());
            row.add(kh.getMaXe());
            row.add(kh.getSLXuat());
            row.add(kh.getDonGiaXuat());
            row.add(kh.getThue());
            row.add(kh.getThanhTien());
            data.add(row);
        }
        DefaultTableModel dtm = new DefaultTableModel(data, column);
        tblchitietphieuxuat.setModel(dtm);

    }
    private void tblphieuxuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblphieuxuatMouseClicked
        // TODO add your handling code here:
        row_table_PhieuXuat = tblphieuxuat.getSelectedRow();
        if (them_CTPN == true) {
            txtmahdctpx.setText(listPhieuXuat.get(row_table_PhieuXuat).getMaPhieuXuat());
        }
        timkiem_ChiTietPhieuXuat();
    }//GEN-LAST:event_tblphieuxuatMouseClicked

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        them_PhieuXuat = false;
        txtmahdpx.setEnabled(false);
        if (row_table_PhieuXuat < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập dòng của bảng muốn sửa!!!");
            return;
        } else {
            txtmahdpx.setText(listPhieuXuat.get(row_table_PhieuXuat).getMaPhieuXuat());
            DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            try {

                Date date = formatter.parse(listPhieuXuat.get(row_table_PhieuXuat).getNgayXuat());
                datechooserngayxuat.setDate(date);
            } catch (ParseException ex) {
                Logger.getLogger(NhanVienGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            model.addElement(listPhieuXuat.get(row_table_PhieuXuat).getMaKhachHang().toString().trim());
            model.setSelectedItem(model.getElementAt(0));
            PhieuXuatGUI.cbbmakh.setModel(model);
            txtmahdpx.setEnabled(false);

        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void cbbmaxeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbmaxeMouseClicked
        // TODO add your handling code here:
        TableXe tblncc = new TableXe();
        value = 1;
        tblncc.setVisible(true);
    }//GEN-LAST:event_cbbmaxeMouseClicked

    private void cbbmaxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbmaxeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbmaxeActionPerformed
    boolean Check_SoLuong() {
        int soluongton = PhieuXuatdll.Get_SoLuong(cbbmaxe.getSelectedItem().toString());

        if (soluongton - (Integer) spnsoluong.getValue() < 0) {
            return false;
        }
        return true;

    }
    private void btnluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluuActionPerformed
        // TODO add your handling code here:
        if (them_CTPN == true) {
            if (Integer.parseInt(spnsoluong.getValue().toString()) == 0 ||cbbmaxe.getSelectedItem()==null) {
                JOptionPane.showMessageDialog(this, "Bạn phải nhập đầy đủ thông tin!!!");
                return;
            }
            if (Check_SoLuong() == false) {
                JOptionPane.showMessageDialog(this, "Số lượng hàng không đủ!!!");
                return;
            }
             else {

                ArrayList dong = CTPNdll.CheckID(txtmahdctpx.getText(), cbbmaxe.getSelectedItem().toString());
                if (dong.size() != 0) {
                    JOptionPane.showMessageDialog(this, "Mã phiếu nhập đã bị trùng mời bạn nhâp lại!!!");
                    return;
                } else {
                    try {
                        ChiTietPhieuXuat nv = new ChiTietPhieuXuat();
                        nv.setMaPhieuXuat(txtmahdctpx.getText());
                        nv.setMaXe(cbbmaxe.getSelectedItem().toString());
                        nv.setSLXuat(spnsoluong.getValue().toString());
                        nv.setDonGiaXuat(txtdongia.getText());
                        nv.setThue(txtthue.getText());
                        if (CTPNdll.AddData(nv) == true) {
                            JOptionPane.showMessageDialog(this, "Thêm thành công!!!");
                        } else {
                            JOptionPane.showMessageDialog(this, "Bạn đã nhập trùng Mã Phiếu Nhập");
                        }

                    } catch (Exception e) {

                    }

                }
            }

        } else if (Check_SoLuong() == false) {
            JOptionPane.showMessageDialog(this, "Số lượng hàng không đủ!!!");
            return;
        } else {
            try {
                ChiTietPhieuXuat nv = new ChiTietPhieuXuat();
                nv.setMaPhieuXuat(txtmahdctpx.getText());
                nv.setMaXe(cbbmaxe.getSelectedItem().toString());
                nv.setSLXuat(spnsoluong.getValue().toString());
                nv.setDonGiaXuat(txtdongia.getText());
                nv.setThue(txtthue.getText());

                if (CTPNdll.updateData(nv) == true) {
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công!!!");
                } else {
                    JOptionPane.showMessageDialog(this, "Bạn chưa chọn điều khiển!!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
                Biding_ChiTietPhieuXuat();

            } catch (Exception e) {

            }

        }
        LamMoi_ChiTietPhieuXuat();
        timkiem_ChiTietPhieuXuat();
    }//GEN-LAST:event_btnluuActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        if (row_table_CTPX < 0) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập dòng của bảng muốn sửa!!!");
            return;
        } else {

            them_CTPN = false;
            //                txtmaphieunhap.setText(listPhieuXuat.get(row_table_PhieuXuat).getMaPhieuXuat());
            txtthue.setText(listChiTietPhieuXuat.get(row_table_CTPX).getThue());
            spnsoluong.setValue(Integer.valueOf(listChiTietPhieuXuat.get(row_table_CTPX).getSLXuat().trim()));
            txtmahdctpx.setText(listChiTietPhieuXuat.get(row_table_CTPX).getMaPhieuXuat());
            txtdongia.setText(listChiTietPhieuXuat.get(row_table_CTPX).getDonGiaXuat());
            DefaultComboBoxModel model = new DefaultComboBoxModel();
            model.addElement(listChiTietPhieuXuat.get(row_table_CTPX).getMaXe().toString().trim());
            model.setSelectedItem(model.getElementAt(0));
            cbbmaxe.setModel(model);
            btnthem.setEnabled(false);
            btnxoa.setEnabled(false);
            cbbmaxe.setEnabled(false);
    }//GEN-LAST:event_btnsuaActionPerformed
    }
    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        ChiTietPhieuXuat nv = new ChiTietPhieuXuat();
        if (row_table_CTPX >= 0) {
            nv.setMaPhieuXuat(tblchitietphieuxuat.getValueAt(row_table_CTPX, 0).toString());
            nv.setMaXe(tblchitietphieuxuat.getValueAt(row_table_CTPX, 1).toString());
            int dialogResult = JOptionPane.showConfirmDialog(this, "Bạn muốn xóa bản ghi?", "Cảnh báo", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                if (CTPNdll.deleteData(nv)) {

                    JOptionPane.showMessageDialog(this, "Xóa thành công!");
                    timkiem_ChiTietPhieuXuat();
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa không thành công!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chọn bạn ghi cần xóa trước");
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        
        if (row_table_PhieuXuat==-1) {
            JOptionPane.showMessageDialog(this, "Bạn hãy chọn dòng bảng phiếu xuất!!! ", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {
            txtmahdctpx.setText(listPhieuXuat.get(row_table_PhieuXuat).getMaPhieuXuat());
            btnsua.setEnabled(false);
            btnxoa.setEnabled(false);
            them_CTPN = true;
        }


    }//GEN-LAST:event_btnthemActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(row_table_PhieuXuat>=0)
        {
     
       timkiem_ChiTietPhieuXuat();
        }
        else
            Biding_ChiTietPhieuXuat();
           LamMoi_ChiTietPhieuXuat();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void tblchitietphieuxuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblchitietphieuxuatMouseClicked
        // TODO add your handling code here:
        row_table_CTPX = tblchitietphieuxuat.getSelectedRow();
    }//GEN-LAST:event_tblchitietphieuxuatMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (row_table_PhieuXuat == -1) {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn dòng muốn in hoá đơn!!!");
            return;
        }
        Report.s1 = listPhieuXuat.get(row_table_PhieuXuat).getMaPhieuXuat();
        Report.number=0;
        try {
            Report.InHoaDon();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PhieuXuatGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(PhieuXuatGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhieuXuatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhieuXuatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhieuXuatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhieuXuatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhieuXuatGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnluu;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    public static javax.swing.JComboBox<String> cbbmakh;
    public static javax.swing.JComboBox<String> cbbmaxe;
    private com.toedter.calendar.JDateChooser datechooserngayxuat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSpinner spnsoluong;
    private javax.swing.JTable tblchitietphieuxuat;
    private javax.swing.JTable tblphieuxuat;
    public static javax.swing.JTextField txtdongia;
    private javax.swing.JTextField txtmahdctpx;
    private javax.swing.JTextField txtmahdpx;
    private javax.swing.JTextField txtmanhanvien;
    private javax.swing.JTextField txtsearchhd;
    private javax.swing.JTextField txtthue;
    // End of variables declaration//GEN-END:variables
}
